Key renewal pilot amsterdam (v2)
privacybydesign/pbdf-schememanager pull request #98
Opened 2023-04-25 09:21 UTC by dmeijboom

Keys for the `pilot-amsterdam` expired at March 18, 2023 (see the [previous pull-request](https://github.com/privacybydesign/pbdf-schememanager/pull/69)).

2023-04-25 20:35 UTC, MikeClickr commented
Thanks @dmeijboom I trust this ne public key is exact what we need. So I hope SIDN will check and merge it. Thanks!

2023-04-26 12:06 UTC, dmeijboom commented
> @dmeijboom I see the generated key is not big enough to support all attributes you're issuing (14). Please check the the documentation to do so: https://irma.app/docs/issuer/#generating-irma-issuer-keys
> 
> Specifically this part:
> 
> _If one of your credentials contains more than 10 attributes, then that amount of attributes increased by 2 (to account for [the secret key and metadata attributes](https://irma.app/docs/overview#special-attributes)) must be passed to the -a or --numattributes flag, to ensure that the new public key supports the required amount of attributes._
> 
> Since you are issuing 14 attributes, this value must be at least 16.

Thanks for the heads-up, fixed!

2023-04-26 12:08 UTC, bobhageman approved these changes

2023-04-26 13:06 UTC, sanderhollaar requested changes
public key needs to be verified

2023-04-26 13:19 UTC, sanderhollaar submitted a review, later dismissed

2023-05-15 11:22 UTC, sanderhollaar approved these changes

2023-05-15 11:27 UTC, bobhageman approved these changes

2023-05-15 11:28 UTC, merged